### ISSUE TITLE
Add support for one class-SVM 

### ISSUE THREAD

**Issue by gilad19** [jpmml/r2pmml#17]

**Comment by vruusmann** [comment]
Can you clarify, which R package/function interests you? Is it `kernlab::ksvm(, type = "one-svm")`, `e1071::svm(.., type = "one-classification")`, or something completely different?

**Comment by gilad19** [comment]
Hi, 

Thanks.
I actually interested in both (kernlab::ksvm and e1071::svm). I guess if I was asked to choose I would pick kernlab::ksvm but it doesn't really matter (by the way, if I am not wrong the type of ksvm is "one-svc"). 

Thank again!

**Comment by gilad19** [comment]
Great, thanks a lot!!!

**Comment by korczykowska** [comment]
Is it possible to apply _r2pmml_ for another type like c-classification?

**Comment by vruusmann** [comment]
@korczykowska If you have questions, then please open new issue(s), instead of "reusing" old and already closed issues.

Here is a list of supported `e1071::svm` parameterizations: https://github.com/jpmml/jpmml-r/blob/master/src/test/R/svm.R

By scrolling through this code, I can't tell right away if `C-classification` is already supported or not (perhaps it's the default for all classifiers). Again, it's your responsibility to provide with a reproducible test case that it's not supported at the moment (sorry, I'm busy working on many things, and I don't have time to verify each claim made against the project).
