### ISSUE TITLE
installation of r2pmml fails with error about R version

### ISSUE THREAD

**Issue by robert-dodier** [jpmml/r2pmml#48]
Hi, I'm hoping to use r2pmml. I am working with R 3.5.0 (via RStudio 1.1.447) on MacOS High Sierra 10.13.6. When I try to install r2pmml I get the following error:

```
> install.packages("r2pmml")
Warning in install.packages :
  package ‘r2pmml’ is not available (for R version 3.5.0)
```

I gather that r2pmml is expecting an earlier version of R. Is there a way I can work around this? Is it possible that it might be as simple as changing the expected version in a configuration file or something like that? Any advice is greatly appreciated.

**Comment by vruusmann** [comment]
> package ‘r2pmml’ is not available (for R version 3.5.0)

This error would happen with any R version, because the `r2pmml` package is not available via the CRAN repository (or any other repository).

You would need to install it directly from GitHub using the `devtools` package, exactly as detailed in the README file:
https://github.com/jpmml/r2pmml#installation
